### ISSUE TITLE
Typo in blog post

### ISSUE THREAD

**Issue by posidonius** [daanbeverdam/checkout-block-provider#2]
There's a typo in the blog post version of `checkout_index_index.xml`

`VendorName/ModuleName/js/view/cms-block`

Above should be stated as:

`VendorName_ModuleName/js/view/cms-block`

The corresponding line in the GitHub version of this file is correct:

`DaanBeverdam_CheckoutBlockProvider/js/view/cms-block`

Excellent blog post. Thanks!

**Comment by progear-dev** [comment]
data-bind="html: window.checkoutConfig.cms_block" works only when you use plain HTML as value of window.checkoutConfig.cms_block.

But when I have cms block where I use widget call like mageInit="{'widgetName': {}}"? It doesn't work.
What I have to do and where?

Thanks in advance

**Comment by daanbeverdam** [comment]
Thanks @posidonius, I've updated the blogpost!

@progear-dev your question is unrelated to this issue, and a bit beyond the scope of this module. I don't think it is possible to render dynamic content in a CMS block this way.
